#!/usr/bin/env bash

set -e

BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
ROOT_DIR=$(dirname "${BIN_DIR}")

MAGENTO_VERSION=2.4.5
MAGENTO_EDITION=CE # CE(community), EE(enterprise), ECE(cloud)
DOMAIN=magento2.docker

# For images for docker-compose.yml in dbin/build-compose
# https://github.com/magento/magento-cloud-docker/releases
IMAGE_VERSION=1.3.2

# https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
PHP_VERSION=8.1
NGINX_VERSION=1.19
MYSQL_VERSION=10.4
REDIS_VERSION=6.2
OS_VERSION=1.2 # Opensearch
ES_VERSION=false # Elasticsearch

PHP_CLI_IMAGE="magento/magento-cloud-docker-php:${PHP_VERSION}-cli-${IMAGE_VERSION}"

