#!/usr/bin/env bash

set -e

BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
source "${BIN_DIR}"/config

cd "${ROOT_DIR}"

if [ -z "$1" ]; then
    dbin/docker-compose exec -u root -T fpm chown -R www:www /app
else
    dbin/docker-compose exec -u root -T fpm chown -R www:www /app/"$1"
fi

echo "Filesystem ownerships fixed."
